import {
  CoinVerticalIcon,
  LightningIcon,
  LockKeyIcon,
} from "@phosphor-icons/react";

export const supppotedCoin = [
  {
    id: crypto.randomUUID(),
    name: "Bitcoin",
    image: "/assets/coins/coin-1.png",
  },
  {
    id: crypto.randomUUID(),
    name: "Ethereum",
    image: "/assets/coins/coin-2.png",
  },
  {
    id: crypto.randomUUID(),
    name: "Tether USD",
    image: "/assets/coins/coin-3.png",
  },
  {
    id: crypto.randomUUID(),
    name: "Ripple",
    image: "/assets/coins/coin-4.png",
  },
  {
    id: crypto.randomUUID(),
    name: "Binance",
    image: "/assets/coins/coin-5.png",
  },
  {
    id: crypto.randomUUID(),
    name: "Solana",
    image: "/assets/coins/coin-6.png",
  },
  {
    id: crypto.randomUUID(),
    name: "USD Coin",
    image: "/assets/coins/coin-7.png",
  },
  {
    id: crypto.randomUUID(),
    name: "Tronix",
    image: "/assets/coins/coin-8.png",
  },
  {
    id: crypto.randomUUID(),
    name: "Doge Coin",
    image: "/assets/coins/coin-9.png",
  },
  {
    id: crypto.randomUUID(),
    name: "Cardano",
    image: "/assets/coins/coin-10.png",
  },
];

export const features = [
  {
    id: crypto.randomUUID(),
    title: "Rock-Solid Security",
    description:
      "Every transaction is protected by end-to-end protection, secure smart routing, and a 24/7 system. You can swap without thinking, 'Is it safe?', because it is safe.",
    icon: LockKeyIcon,
  },
  {
    id: crypto.randomUUID(),
    title: "Fee feels Make Sense",
    description:
      "Super low fees with no hidden BS. NanoSwap finds the most efficient route so you get the optimal swap without draining your wallet. Economical yet fast.",
    icon: CoinVerticalIcon,
  },
  {
    id: crypto.randomUUID(),
    title: "Lightning-Level Execution",
    description:
      "NanoSwap gets you to your destination without delay. The NanoSwap engine is designed for maximum speed—so you don't have to wait long.",
    icon: LightningIcon,
  },
];

export const markets = {
  gainers: [
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-11.png",
      token: "Black Phoenix",
      symbol: "BPX",
      price: 1.59,
      change_24h: 4447.76,
      volume_24h: "888.13M",
      market_cap: "15.24B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-12.png",
      token: "NOT Coin",
      symbol: "NOT",
      price: 0.02316,
      change_24h: 477.57,
      volume_24h: "911M",
      market_cap: "2.14B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-13.png",
      token: "MEGA Coin",
      symbol: "PEOPLE",
      price: 0.000204,
      change_24h: 416.68,
      volume_24h: "1.32B",
      market_cap: "24B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-14.png",
      token: "Turbo Trump",
      symbol: "TURBO",
      price: 384.89,
      change_24h: 0.032,
      volume_24h: "992M",
      market_cap: "45.11B",
    },
  ],
  market_overview: [
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-1.png",
      token: "Bitcoin",
      symbol: "BTC",
      price: 91366.08,
      change_24h: 0.96,
      volume_24h: "39B",
      market_cap: "1.82T",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-2.png",
      token: "Ethereum",
      symbol: "ETH",
      price: 3034.82,
      change_24h: 2.05,
      volume_24h: "3.4B",
      market_cap: "366B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-3.png",
      token: "Tether USD",
      symbol: "USDT",
      price: 1.3,
      change_24h: -0.03,
      volume_24h: "57.48B",
      market_cap: "184.62B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-4.png",
      token: "Ripple",
      symbol: "XRP",
      price: 2.19,
      change_24h: 1.17,
      volume_24h: "1.79B",
      market_cap: "132.65B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-5.png",
      token: "Binance",
      symbol: "BNB",
      price: 895.21,
      change_24h: 2.67,
      volume_24h: "1.41B",
      market_cap: "123.28B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-6.png",
      token: "Solana",
      symbol: "SOL",
      price: 138.12,
      change_24h: 1.97,
      volume_24h: "2.9B",
      market_cap: "77.27B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-7.png",
      token: "USD Coin",
      symbol: "USDC",
      price: 0.9998,
      change_24h: -0.01,
      volume_24h: "5.5B",
      market_cap: "76.54B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-8.png",
      token: "Tronix",
      symbol: "TRON",
      price: 0.2823,
      change_24h: 0.59,
      volume_24h: "370.23M",
      market_cap: "26.73B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-9.png",
      token: "Doge Coin",
      symbol: "DOGE",
      price: 0.1497,
      change_24h: 1.25,
      volume_24h: "670.69M",
      market_cap: "22.77B",
    },
    {
      id: crypto.randomUUID(),
      image: "/assets/coins/coin-10.png",
      token: "Cardano",
      symbol: "ADA",
      price: 0.4245,
      change_24h: 2.68,
      volume_24h: "386.63M",
      market_cap: "15.24B",
    },
  ],
};
